name: Contribution Activity
on:
    schedule:
        - cron: "*/30 * * * *"
    workflow_dispatch:
jobs:
    build:
        name: Update this repo's README with recent contribution activity
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: GitHub - Activity - Readme
              uses: jamesgeorge007/github-activity-readme
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
