name: Recent GitHub Activity

on:
    schedule:
        - cron: "0 */24 * * *"
    workflow_dispatch:

jobs:
    build:
        name: Update the README with recent GitHub activity
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3
            - uses: jamesgeorge007/github-activity-readme@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
